### ISSUE TITLE
Error: tried to lookup a topic but connection was closed, reconnecting...

### ISSUE THREAD

**Issue by AhiVT** [streamnative/pulsar-rs#105]
I am successfully authenticating (via JWT) with my Pulsar instance, but when I attempt to create a producer on a valid, existing topic I get an error that Service Discovery is disconnected. Attempting with authentication disabled yields the same result. Using `pulsar-client` produces messages as expected. I am on `master`@ 81e38fafbbecbbd6d00fec9d818ee183b8d9085d

**Comment by Geal** [comment]
hello, could you show the code and the logs?

**Comment by Geal** [comment]
do you use a pulsar proxy or not?

**Comment by AhiVT** [comment]
@Geal no proxy, will post code snippet later today as a gist

**Comment by AhiVT** [comment]
@Geal https://gist.github.com/Dunklheit/d12586f9f210bdb97011462d0cbb2f92

**Comment by Geal** [comment]
I'm not sure it is supposed to work of you create two runtimes. What happens if you write `let mut runtime = Runtime::new()
  .unwrap()` and use that variable both to create the client and the producer?

**Comment by AhiVT** [comment]
I will give this a shot shortly and follow up with my results!

**Comment by AhiVT** [comment]
@Geal Your proposed solution worked! Perhaps Pulsar isn't checking if runtimes are the same when spawning producers, consumers, etc? Will runtimes be checked in future versions of pulsar-rs?

**Comment by Geal** [comment]
in the previous versions, the executor would be passed as argument, but it complicated the code for various reasons. In any case it does not make much sense to use multiple runtimes: the one used to create the client would register the connection, then when creating the producer we would try to use that same connection from another runtime?
Maybe it worked before but it won't be possible in this version. Could you tell me a bit about your use case? I don't see why you would use two different runtimes without separating them through message passing
