### ISSUE TITLE
Dead Letter Queue policy for Consumer

### ISSUE THREAD

**Issue by rtakasu** [streamnative/pulsar-rs#107]
Is there any plan to implement a DLQ policy for the Consumer? Similar to what other client libraries have (eg. DeadLetterPolicy for Java client: https://pulsar.apache.org/docs/en/client-libraries-java/)

**Comment by Geal** [comment]
yes, but probably not in this release (we need to ship that 1.0 soon)

**Comment by stearnsc** [comment]
Closed by https://github.com/wyyerd/pulsar-rs/pull/110
