### ISSUE TITLE
[Question] How can i use token with auth

### ISSUE THREAD

**Issue by liangyuanpeng** [streamnative/pulsar-rs#111]
This repo is cool thing. Thanks for your working.

I am not very familiar with rust. and i have no idea of use token.

I had try:

```
let addr = "pulsar://127.0.0.1:6650";
    let pulsar: Pulsar<TokioExecutor> = Pulsar::builder(addr)
    .with_auth(Connection:::Authentication{
        
    })
```
and it's not working.

Thanks any help!!

**Comment by stearnsc** [comment]
I don't have a test environment in front of me, but I believe usage is:
```rust
    let token: String = ...;
    let pulsar = Pulsar::builder(addr)
        .with_auth(Authentication {
            name: "token".to_owned(),
            data: token.into_bytes(),
        })
        .build()?;
```

Does that work?

**Comment by liangyuanpeng** [comment]
@stearnsc 
Thanks for your reply. 

I just got:
```
cannot find struct, variant or union type `Authentication` in this scope
```

My code:
```
 ...
let pulsar: Pulsar<TokioExecutor> = Pulsar::builder(addr)
    .with_auth(Authentication{
        name: "token".to_owned(),
        data: &token.into_bytes(),
    })
    .build()
    .await?;
  ...
```

**Comment by stearnsc** [comment]
You have to import it:
```rust
use pulsar::Authentication;
```

**Comment by liangyuanpeng** [comment]
Yes, Thanks!

I think the token is ok.But i got new error:

```
    Finished dev [unoptimized + debuginfo] target(s) in 10.50s
     Running `target/debug/examples/producer`
begin create producer
Error: ServiceDiscovery(Connection(Io(Os { code: 110, kind: TimedOut, message: "Connection timed out" })))
```

My code:
```
println!("begin create producer");
    let mut producer = pulsar
        .producer()
        .with_topic("non-persistent://public/default/test")
        .with_name("my producer")
        .with_options(producer::ProducerOptions {
            schema: Some(proto::Schema {
                type_: proto::schema::Type::String as i32,
                ..Default::default()
            }),
            ..Default::default()
        })
        .build()
        .await?;
    println!("created producer ");
```


I had try java-client and it's working of topic `non-persistent://public/default/test`.

I will continue to try later.

**Comment by Geal** [comment]
you can use this example to help https://github.com/wyyerd/pulsar-rs/blob/master/examples/producer.rs
Add a logger as in the example, this will be much easier to debug the issue

**Comment by liangyuanpeng** [comment]
> you can use this example to help https://github.com/wyyerd/pulsar-rs/blob/master/examples/producer.rs
> Add a logger as in the example, this will be much easier to debug the issue

I just got the `x messages ` in producer , and consumer nothing


```
1 messages
2 messages
3 messages
4 messages
5 messages
6 messages
...
```

Pulsar Version : 2.6.0
Pulsar-rs Version: 1.0.0

**Comment by liangyuanpeng** [comment]
> you can use this example to help https://github.com/wyyerd/pulsar-rs/blob/master/examples/producer.rs
 > Add a logger as in the example, this will be much easier to debug the issue
 
 I just got the `x messages ` in producer , and consumer nothing
 From https://github.com/wyyerd/pulsar-rs/blob/master/examples/producer.rs and https://github.com/wyyerd/pulsar-rs/blob/master/examples/consumer.rs
 ```
 1 messages
 2 messages
 3 messages
 4 messages
 5 messages
 6 messages
 ...
 ```
 
 Pulsar Version : 2.6.0
 Pulsar-rs Version: 1.0.0

**Comment by Geal** [comment]
@liangyuanpeng could you provide trace level logs? using [env_logger](https://docs.rs/env_logger/0.8.2/env_logger/) or other crates

**Comment by Geal** [comment]
closing this for now, feel free to reopen if the problem reappears
