### ISSUE TITLE
Consumer stops consuming messages

### ISSUE THREAD

**Issue by ntv-drraksa** [streamnative/pulsar-rs#118]
Hello there,

I have found an issue with the consumer. (Connect to Pulsar version 2.6)
If there is no new message pushed to the queue for a while (around 4 - 5 minutes+), the consumer will stop consuming new messages even a new message is already pushed in the queue after that (Get stuck at  `Consuming a new message`  log,  `Got a new message` log is never printed out after it hangs)

Here's the code that I use

```rust
let pulsar: pulsar::Pulsar<_> = pulsar::Pulsar::builder(pulsar_setting.url, TokioExecutor)
        .with_certificate_chain_file(pulsar_setting.cert_file_path.to_owned())
        .unwrap()
        .build()
        .await?;

let mut consumer: pulsar::Consumer<PaymentHistoryLog, _> = pulsar
        .consumer()
        .with_consumer_name(format!("bg-service-{}", suffix_name))
        .with_topic(pulsar_setting.charge_topic)
        .with_subscription_type(pulsar::SubType::Exclusive)
        .with_subscription("charge.v1")
        .build()
        .await?;

loop {
    log::info!("Consuming a new message");

    let result = consumer.next().await;

    log::info!("Got a new message");

    match result {
        Some(Ok(msg)) => {
            match msg.deserialize() {
                Ok(data) => {
                    log::info!("Got data of user id {}", &data.user_id);
                }
                Err(e) => {
                    log::error!("Failed to deserialize message: {:?}", e);
                }
            }
        }
        Some(Err(error)) => {
            log::error!("Got error while consuming: {:?}", error)
        }
        None => {
            log::warn!("Got `None` while consuming")
        }
    }
}
```

Do you guys have any suggestions? Please let me know if you need more detail.

**Comment by ntv-drraksa** [comment]
~~This is solved after upgrading Pulsar to version 2.6.1~~

Still not working

**Comment by addisonj** [comment]
I am not sure this library is currently supporting the `CloseConsumer` command that can be sent by the broker, which indicates to the client it should re-do topic discovery and re-establish the consumer. 

This is how pulsar signals to the client that it should re-connect after a topic is migrated to a new broker or the broker is gracefully restarted

**Comment by Geal** [comment]
I don't think it is supported, I'll add it

**Comment by Geal** [comment]
CloseConsumer is handled in b74e454

@ntv-drraksa could you test again? If it does not work, could you show logs with level "trace"?

**Comment by Geal** [comment]
closing this for now, feel free to reopen if the problem reappears
