### ISSUE TITLE
seek(timestamp) method

### ISSUE THREAD

**Issue by DonghunLouisLee** [streamnative/pulsar-rs#124]
would it be possible to have seek(timestamp) api implemented? 

https://pulsar.apache.org/api/cpp/2.6.0-SNAPSHOT/classpulsar_1_1_consumer.html

**Comment by DonghunLouisLee** [comment]
i can work on this if needed but i wasn't sure about the project status..

**Comment by Geal** [comment]
done in 56bd666, thanks!
