### ISSUE TITLE
pulsar v2.0

### ISSUE THREAD

**Issue by Geal** [streamnative/pulsar-rs#130]
With the release of tokio 1.0, we should probably make a new major version to support it. While it is probably possible to keep support for both versions of tokio at the same time, it will be cumbersome, especially when trying to use different versions of the bytes crate.

So, I propose:
- releasing a 1.1.0 at e4fd9251a295cd (or after I send a few small fixes)
- releasing  2.0 with #128 that provides the migration to tokio 1.0

@stearnsc what do you think? Do you have any breaking changes to add while we're at it?

side note: I'm not too attached to major version numbers, if we have big changes to do in the future, a 3.0 will be fine too :wink:

**Comment by KannarFr** [comment]
yey!

**Comment by Geal** [comment]
@stearnsc 1.1.0 can be published at 01672793b58161

**Comment by Geal** [comment]
@stearnsc I batched dependency updates in 5196ffd, that should be enough for the 1.1. I'd really like this to get out soon, so we can then have another version with the new tokio, it's holding back some of our projects.
If you don't have the time to handle the release, you could add me to the owners on crates.io, I'll take care of it

**Comment by Geal** [comment]
The [2.0 branch](https://github.com/wyyerd/pulsar-rs/tree/2.0) now contains #128 rebased on master

**Comment by Geal** [comment]
@stearnsc ping! Could tou add me to the owners on crates.io, so I can release new versions more smoothly? Also, if it's alright, I can handle the administrative stuff to move the project to the ASF

**Comment by Geal** [comment]
@stearnsc thank you for adding me to the owners. There's a published 1.1 version containing the recent changes on error management, retries, etc. A new 1.0 branch is there to hold possible bugfixes for this version. The master branch holds the changes for the 2.0 version, including the update to tokio 1.0, a new connection timeout check, and an update to the 2.7.0 binary protocol.
I'm planning to release the 2.0 tomorrow if we don't see any big issue.

**Comment by stearnsc** [comment]
@Geal awesome, thanks for making this happen. And feel free to handle the apache administrative stuff as well if you like - we have an upcoming launch at wyyerd, so I've been totally swamped for the last couple months and lot of stuff has gotten dropped :(

**Comment by Geal** [comment]
so, 2 weeks and a lot more tests later, 2.0 is published! https://crates.io/crates/pulsar
