### ISSUE TITLE
add a method for setting initial position for ConsumerOptions explicitly

### ISSUE THREAD

**Issue by DonghunLouisLee** [streamnative/pulsar-rs#131]
Currently, to set the subscription to earliest, you have to do 

.with_options(ConsumerOptions { initial_position: Some(1), ..Default::default() }) 

which is good enough but i think it might be better if we can add a method for changing the initial position explicitly like 
http://pulsar.apache.org/api/client/2.4.2/org/apache/pulsar/client/api/SubscriptionInitialPosition.html

I can work on this if necessary! 
Thanks

**Comment by Geal** [comment]
sure, it would be nice!

**Comment by Geal** [comment]
I added an enum in https://github.com/wyyerd/pulsar-rs/commit/b06e67de5df21eb72b96d98cc0286d408fe1c057
I'll replace the `Option<i32>` in  `ConsumerOptions` on the next major release as it would be a breaking change
