### ISSUE TITLE
how to unsubscribe a topic for a consumer

### ISSUE THREAD

**Issue by dylankyc** [streamnative/pulsar-rs#141]
I want to unsubscribe a topic for consumer when process receiving an interrupt signal, is there any `unsubscribe` method?

Thanks

**Comment by Geal** [comment]
removing a subscriber requires using the HTTP API, and we do not yet include one. You can create a consumer with options setting `durable` to false though: https://docs.rs/pulsar/2.0.0/pulsar/consumer/struct.ConsumerOptions.html#structfield.durable

**Comment by simon-fu** [comment]
how to send CommandUnsubscribe to broker?

**Comment by Geal** [comment]
pulsar 4.1.0 is now released with the `Command::unsubscribe()` method: b78def7
