### ISSUE TITLE
subtype is currently not pub

### ISSUE THREAD

**Issue by DonghunLouisLee** [streamnative/pulsar-rs#151]
Before pulsarApi.proto was converted to rust code but now it seems protoc is being used for auto compilation. Due to this, i think enum SubType is not pub anymore which will cause problem when calling with_subscription() method.

**Comment by Geal** [comment]
which version are you testing? `SubType` is public and is accessible here in 2.0.0: https://docs.rs/pulsar/2.0.0/pulsar/message/proto/command_subscribe/enum.SubType.html
