### ISSUE TITLE
Make message_id accessible for a Consumer Message

### ISSUE THREAD

**Issue by sammoh94** [streamnative/pulsar-rs#154]
Currently, the `message_id` field is not accessible but don't we need it if we need to position the cursor to a specific point in the stream?

Happy to submit a PR for this but let me know if I am missing an alternate approach to do this that is already available

Reference: https://github.com/wyyerd/pulsar-rs/blob/master/src/consumer.rs#L1684

**Comment by BewareMyPower** [comment]
I think exposing the field as `pub` is reasonable. The official Java client also provides a method to expose message id.

But it should be noted that `message_id` is a protobuf type. I see other clients like Java and C++ all wrap the `proto::MessageIdData` into a new type. I'm not sure if it's proper to expose it directly in Rust.
