### ISSUE TITLE
Connection Loss During Consumer Poll

### ISSUE THREAD

**Issue by cameronpickham** [streamnative/pulsar-rs#156]
If a consumer's connection becomes unusable while it is polling for new messages, how is this handled? Should there be a seamless reconnect? Does it use the same connection retry options that are used when the initial connection attempt fails?

**Comment by dylankyc** [comment]
It seems there are reconnect operations both when creating a consumer in [TopicConsumer::new](https://github.com/wyyerd/pulsar-rs/blob/master/src/consumer.rs#L416) and consuming messages after [ConsumerEngine](https://github.com/wyyerd/pulsar-rs/blob/master/src/consumer.rs#L692) started , but there's no retry when consuming messages, if reconnect fails in engine, the loop in engine method will stop.

**Comment by Geal** [comment]
FYI I'm in the process of fixing issues around that, the next version should be more stable

**Comment by whisust** [comment]
As a workaround, I've used this:
```rust
info!("Starting the consumer loop");
loop {
    let mut consumer = libpulsar::new_consumer::<VideoEvent>(&pulsar_conn, &topic).await?;
    info!("Consumer started");
    let e = consumer_loop(consumer).await;
    warn!("Consumer was closed because of {:?}, restarting it...", e);
}
```
