### ISSUE TITLE
cargo build fail with nom v7.0.0-alpha2

### ISSUE THREAD

**Issue by simon-fu** [streamnative/pulsar-rs#167]
Recently, nom upgrade to  v7.0.0-alpha2 , and cargo build fail with "error: cannot find macro `named` in this scope

**Comment by juanviamonte** [comment]
@simon-fu this might help meanwhile `pulsar = {git = "https://github.com/wyyerd/pulsar-rs"}`

**Comment by simon-fu** [comment]
fix it by adding  this line to  Cargo.toml  of my project 
nom = { version="=7.0.0-alpha1", default-features=false, features=["alloc"] }

**Comment by Geal** [comment]
Pulsar 4.1 is now released with nom 7.0: fb04666
