### ISSUE TITLE
Add note for release

### ISSUE THREAD

**Issue by liangyuanpeng** [streamnative/pulsar-rs#173]
Now, we can not know what resolved any problem or issue in release.  It would be greate if we can add some note when release. And i can help to trace related issue when release.

![image](https://user-images.githubusercontent.com/28711504/134040617-74a7ba9b-de2f-447e-a427-1a0c7e76b94d.png)

**Comment by Geal** [comment]
Sure, a changelog file would be great

**Comment by tisonkun** [comment]
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/18818196/213248296-31de44e2-4c83-4206-b06d-4d8350393cc0.png">

I can update the latest releases note by leveraging GitHub generate release note feature.

Close as done. If you have more concrete workflow to generate notes or maintain a changelog, you're welcome to propose it.
