### ISSUE TITLE
Hi, is this project still maintained?

### ISSUE THREAD

**Issue by hezhangjian** [streamnative/pulsar-rs#198]
Hello, guys, I want to know Is that project still maintained? I saw the last updated is on year 2021.

**Comment by doehyunbaek** [comment]
There's fork by streamnative which seems to be more actively maintained if you'red interested(https://github.com/streamnative/pulsar-rs).

**Comment by stearnsc** [comment]
Hi! Great question - answer is not really, but I'm motivated to get it so. Context is I originally wrote this when I was working as a developer, and we still use it heavily in production, but I'm now a manager and nobody else at Wyyerd is familiar with the codebase. @Geal mostly took it over while, but after he changed jobs we're back in a bit of no man's land. I've reached out to the streamnative folks to see if they'd be interested in upstreaming their changes and taking over ownership (issue here: https://github.com/streamnative/pulsar-rs/issues/20).

**Comment by sijie** [comment]
Reposted here for broader visibility: https://github.com/streamnative/pulsar-rs/issues/20#issuecomment-1123212435

**Comment by sijie** [comment]
Hi all, we have completed the transfer and will merge the changes in the fork back. See comment https://github.com/streamnative-oss/sn-pulsar-rs/issues/20#issuecomment-1139304464
