### ISSUE TITLE
new Client and ConnectionManager interfaces

### ISSUE THREAD

**Issue by Geal** [streamnative/pulsar-rs#20]
while working on the service discovery feature, I got an idea of how to make an API that's easy to use.

### Connection manager

Handling connections to a Pulsar cluster is a lot of work. Through a single client, we should be able to connect to multiple brokers, either directly, or through a proxy, in TCP plaintext or over TLS. A broker connection could be shared between multiple producers and consumers. Also, handling authentication.

I explored a way to handle it in the service discovery PR: a function that takes a broker address, and returns a `Future` of `Arc<Connection>`. If the connection exists, we get it immediately, otherwise we try to connect to that broker.

I'd like to extract that from the SD code, and have a `ConnectionManager` struct, that would be created from the following information:
- IP and port of either a broker or the proxy
- authentication data (if available)
- activate TLS or not

This connection manager would handle connecting to other broker, passing along authentication data, creating TLS connections, and answering queries for `Connection` object.
I'm not sure it should reconnect automatically when connections drop, because consumers using them would need to be created again, but it should allow reconnecting if asked to.

When used through SD, the connection manager would be automatically populated with the discovered brokers.
Consumers and producers could be created with connections coming from the manager (they already use a `Arc<Connection>` internally).

### pulsar::Client

This would be a wrapping object that can connect, perform lookups, create producers and consumers, while hiding the protocol details (the current `Connection`, `Consumer`, `Producer` and `ServiceDiscovery` APIs should still be available if people want to get a bit lower in the stack).

It would be created from connection info like the connection manager, and would have methods like these:
- `lookup_topic`/`lookup_partitioned_topic`
- `create_consumer`/`create_producer` from a broker address and a topic name
- `consume_topic`/`consume_partitioned_topic`, possibly creating one consumer per partitioned topic?
- `send_message` to send a single message to a topic

This `Client` interface would hide a lot of boilerplate to implement common use cases.

**Comment by stearnsc** [comment]
I like this idea a lot;
>I'm not sure it should reconnect automatically when connections drop, because consumers using them would need to be created again, but it should allow reconnecting if asked to.

I think refactoring to allow transparently swapping out `Connection`s would be a good move eventually; since all that communication happens over channels, I don't foresee the mechanics being particularly difficult, but there are probably some issues to be worked out to ensure no data loss (from consumers) or duplicate writes (from producers). 

>This would be a wrapping object that can connect, perform lookups, create producers and consumers, while hiding the protocol details (the current Connection, Consumer, Producer and ServiceDiscovery APIs should still be available if people want to get a bit lower in the stack).

I like this a lot. I was thinking about how to ensure we can make use clean and easy for "normal" use cases (multiple brokers, etc), while still making it stupid simple for prototyping, and I think having the normal "create consumer/producer" flow go through the client could solve both cases well.

**Comment by stearnsc** [comment]
resolved by https://github.com/wyyerd/pulsar-rs/pull/22 and https://github.com/wyyerd/pulsar-rs/pull/23
