### ISSUE TITLE
Connection retry not working as intended.

### ISSUE THREAD

**Issue by doehyunbaek** [streamnative/pulsar-rs#207]
While using this client library, it seemed that when connection to pulsar client failed with ConnectionRefused error, such as `Connection(Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))'`, pulsar client did not retry. After I added logging between 309 and 310,

https://github.com/streamnative/pulsar-rs/blob/0d88e24a075c1969a51829d8b3260172976d2e4a/src/connection_manager.rs#L309-L310

I confirmed there was no retry happening.

After reading the code, I found out that the code checking for kind of error, which is 

https://github.com/streamnative/pulsar-rs/blob/0d88e24a075c1969a51829d8b3260172976d2e4a/src/connection_manager.rs#L310-L311

seems to evaluate to always true, as this only evaluates to false when e.kind() is both ConnectionRefused and Timedout, which is impossible. 

Maybe the intent was to use && instead of ||? I changed || to && and retry works as intended.

This change seems to be introduced in https://github.com/streamnative/pulsar-rs/commit/64d3edc6b832da873f5ac251919b824aff131604, if anyone can confirm it's a bug or it is discussed and decided so, I will open a PR applying the suggested fix of || to &&. If I'm mistaken, please correct me.

**Comment by doehyunbaek** [comment]
This commit https://github.com/doehyunbaek/pulsar-rs/commit/057f333df068a900a1a473e45e4d90a5ee227e66 is the proposed change.

**Comment by DonghunLouisLee** [comment]
@doehyunbaek  This is indeed a bug so it would be great if you can go ahead and open a PR for this. Thanks

**Comment by doehyunbaek** [comment]
Opened https://github.com/streamnative/pulsar-rs/pull/208.
