### ISSUE TITLE
Producer send incomplete batch after delay

### ISSUE THREAD

**Issue by KannarFr** [streamnative/pulsar-rs#213]
A producer using batch is waiting for the batch to be full (batch_size reached) to send a message. Whenever the batch is created for a long time if the batch_size is not reached the batch seems not sent.

https://github.com/streamnative/pulsar-rs/blob/c31fc8335e4e321c85e0024aa4189c318a581082/src/producer.rs#L592

**Comment by StevenLeRoux** [comment]
Generally you'd have a trigger that pushes batches whatever the fulfillment of the batch buffer. This trigger should also have a default value but should remain configurable, depending on use cases.

**Comment by miton18** [comment]
linked to https://github.com/streamnative/pulsar-rs/issues/104

**Comment by tisonkun** [comment]
@KannarFr I suspect this is a duplicate of #104. If you can confirm it, we keep only #104.

**Comment by KannarFr** [comment]
It is.
