### ISSUE TITLE
Release 4.1.3?

### ISSUE THREAD

**Issue by tisonkun** [streamnative/pulsar-rs#230]
After v4.1.2 release, we make several bug fixes and code tidy works ([diff](https://github.com/streamnative/pulsar-rs/compare/v4.1.2...master)). Now about three months passed and I encounter a situation that wants the version bump of zstd https://github.com/streamnative/pulsar-rs/commit/b11ee506b5216d31a834c12881b5d022d5cb6580.

Instead of replacing `pulsar = "4.1.2"` with a `git` handle, I'd prefer to have a 4.1.3 release including all these changes.

What do you think? @DonghunLouisLee @sijie @fantapsody @freeznet

**Comment by freeznet** [comment]
Thanks @tisonkun for bringing this up, and +1 for 4.1.3 release.

**Comment by DonghunLouisLee** [comment]
Yup 4.1.3 sounds good

**Comment by tisonkun** [comment]
Thanks for your responses. Now the question is _how to perform the release_.

I can see @Geal and @stearnsc have the owner bit on crates.io. I'm unsure whether they're willing to be the release manager.

Besides, it seems we integrate with @streamnativebot for automatically releasing. But I don't find any instructions about how to work with it. @freeznet @DonghunLouisLee @yaalsn thoughts?

**Comment by yaalsn** [comment]
We can add `Streamnative Bot` app to StreamNative's slack workspace and publish release by using slack command `/release pulsar-rs --branch=<base-branch> --version=<release-version>`

@freeznet @DonghunLouisLee What do you think the base-branch should be? `branch-4.1` or `master`?

**Comment by tisonkun** [comment]
@yaalsn thanks for your input. Although I'd prefer a self-contained release process, it's OK to me currently by asking for a SN member to perform the release.

> What do you think the base-branch should be? branch-4.1 or master?

The to-be-released artifact is all on `master`. I don't know the previous conventions but it seems that we have both `branch-4.1` and `branch-4.1.2` and either of them is out of sync. I'd prefer to perform the release based on master first and have a separate discussion about branching and releasing mechanism topic.

**Comment by yaalsn** [comment]
https://crates.io/crates/pulsar/versions 4.1.3 released! 🎉

**Comment by tisonkun** [comment]
@yaalsn Thanks!

Closed as completed.
