### ISSUE TITLE
Release should update master branch metadata

### ISSUE THREAD

**Issue by tisonkun** [streamnative/pulsar-rs#248]
cc @yaalsn 

Previously, release will update Cargo.toml metadata: https://github.com/streamnative/pulsar-rs/commit/de59974080daa248bfdeaea8510eb72ec8f30bac.

But when releasing 5.0.0 and 5.0.1, only new tag is created, not the master branch. Now I have to update the file manually: https://github.com/streamnative/pulsar-rs/commit/a0496ab31f4dbc0bd3e20053c1c66438cfc256fa

Is it possible to integrate in the release process?

**Comment by tisonkun** [comment]
Interesting. I can see https://github.com/streamnative/pulsar-rs/commit/b70490ce6b5641f507eccb7173dc4fe3ed3c6bb1 now, but it does take a while.

**Comment by yaalsn** [comment]
StreamNative bot only creates a branch and updates the version in this branch, so maybe other owners cherry-pick this commit or merge PR to the master branch.

e.g. https://github.com/streamnative/pulsar-rs/actions/runs/3931244565

**Comment by tisonkun** [comment]
Closing...

We can update it manually now.
