### ISSUE TITLE
Unable to cleanly close a consumer without unsubscribing from a topic

### ISSUE THREAD

**Issue by klaatu01** [streamnative/pulsar-rs#279]
The current behaviour of `TopicConsumer::close` [also unsubscribes](https://github.com/streamnative/pulsar-rs/blob/bd590e0046cf077094d59d79289258c9b84dfbe1/src/consumer/topic.rs#LL265C3-L265C3) from a topic. 

In my organisation, we use pulsar as an event broker between bounded contexts, our topics are persistent, and subscriptions are meant for long-term consumption and should outlive the clients consuming from them.

After digging through both the [GoLang client](https://github.com/apache/pulsar-client-go/blob/27e36250f35094b203483c946bc4406c6119ce62/pulsar/client_impl.go#L265) and [Java client](https://github.com/apache/pulsar/blob/9918bced4465e0b0746a7959550c90cb76ae945f/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#LL1008C41-L1008C41) it seems like neither of these perform and unsubscription on close. 

I can make a PR to either fix this or add a new function for closing without unsubscribing.

**Comment by tisonkun** [comment]
Closed by https://github.com/streamnative/pulsar-rs/pull/278.

Releasing 6.0.0 for this one..

**Comment by tisonkun** [comment]
Released as https://crates.io/crates/pulsar/6.0.0. Thank you @klaatu01!
