### ISSUE TITLE
Is there plan to upgrade to new futures?

### ISSUE THREAD

**Issue by chrislearn** [streamnative/pulsar-rs#54]
Hello, just wonder is there plan to upgrade to futures 0.3 and tokio 0.2?

**Comment by stearnsc** [comment]
Yep, it's in progress, but probably still a couple weeks out so long as I'm the only person working on it. 

I've created a tracking issue https://github.com/wyyerd/pulsar-rs/issues/55 to organize discussion. If you have opinions about how we handle anything during the upgrade, please feel free to chime in there.
