### ISSUE TITLE
Upgrade to futures 0.3

### ISSUE THREAD

**Issue by stearnsc** [streamnative/pulsar-rs#55]
I've started work on the futures 0.3 upgrade, but I think this is probably also a good time to actually solve some of the other major issues I've been thinking about, as they will likely involve breaking changes to the API.

(1) How we handle reconnects. Right now, a disconnect will fail a producer or consumer (at least the single-topic variety), requiring users to manually handle reconnects. In particular, since pulsar is frequently used in cloud applications, I'd like to be resilient to e.g. DNS changes (if a user redeploys their pulsar cluster, it would be nice for existing applications to transparently reconnect to the new cluster). Currently, I'm thinking having a single separate task that handles _all_ of the connections, producers, and consumers might be simplest, but it would be worth verifying that this doesn't negatively affect throughput.

(2) How to handle slowly adding pulsar features without breaking changes each time. Right now, as we slowly build out full functionality, we keep needing to add configurable options to constructors. Right now, each of these requires a minor version bump. One option would be to hide everything behind builders, and just add more `with_<option>(...)` methods. Others?

(3) How to handle spawning tasks for multiple executors. With the increasing popularity of async-std, it seems important to not be tied to the tokio runtime. `futures` exposes a `Spawn` (or really, `SpawnExt`) trait that we can wrap to pass around our own executor, but right now it appears that `async-std` doesn't actually expose anything that implements it, so that might not be a workable solution. Alternatively, we could have client creation return an "engine" future that callers are required to spawn themselves, and internally use channels to pass anything that needs to be handled to that future. We could also use feature-flags to specify runtime. Right now, there are only two major ones (`tokio` and `async-std`), but if the ecosystem grows, this could quickly become untenable.

**Comment by ebkalderon** [comment]
In regards to the second point, I believe that having a `ConsumerBuilder` or `ProducerBuilder` might indeed be a good idea. See [`reqwest::ClientBuilder`](https://docs.rs/reqwest/0.10.1/reqwest/struct.ClientBuilder.html) for an example of how this API could look like.

**Comment by cameronpickham** [comment]
What is the latest on this library being upgraded to the latest Tokio/futures? I'm very interested in using it but am unable to do so because of the outdated dependencies.

**Comment by Geal** [comment]
@cameronpickham I'm working on it, it will take a while to port it to futures 0.3 and async/await

**Comment by Geal** [comment]
done in #71
