### ISSUE TITLE
Handling batched messages

### ISSUE THREAD

**Issue by gperinazzo** [streamnative/pulsar-rs#59]
The current implementation does not deal with batched messages. When pulsar sends a batch of messages, the message payload will contain a sequence of `SingleMessageMetadata` followed by the individual message payload, for each message.

Due to this, a naive implementation of  `DeserializeMessage` will fail when receiving a batched message, as it has to read the `SingleMessageMetadata` before processing the payload.

This also requires #36 to be resolved, as the entire batch must be decompressed.

**Comment by gperinazzo** [comment]
I have been looking at how to implement this. It seems that batched messages handle ack differently from normal messages. On a batched message, the entire batch has a single message ID that has to be acked.

Both the go and C++ implementations track which messages from a given batch have been acked and only send the command to the broker once all messages in the batch are acked. If a batched message is nacked, the entire batch is redelivered, not only the nacked message.

I'm trying to implement this without changing the way that Ack currently works, but how would you prefer this tracking to done? The ways I can think are:
1) Add this tracking to the current AckHandler future, and send it a message whenever a new batched message is created so it can properly track the batch size.
2) Create a separate strucutre to track the batch, either in a new future, or as a shared object that all the messages in the batch ack to instead of the AckHandler.

Alternativaly we can avoid hiding this behaviour from the application, handing it the entire batch of messages, and asking it to ack only if it managed to handle all of them. This has the benefit of making explicit that either the entire batch is acked, or the entire batch will be redelivered.

**Comment by stearnsc** [comment]
I like the idea of modifying the existing `Ack`s to handle when they're part of a batch (maybe an optional field that indicates which message in the batch is being ack'd), and tracking this in the `AckHandler`. The only issue is that to make redelivery transparent, the consumer will need to know which inner-messages have been ack'd so it can filter them out if the parent message gets redelivered. I don't foresee this being particularly difficult, but will require some surgery. 

I'll implement this on the branch I'm hoping to become 1.0 (major rewrite with futures 0.3), but that might still be a ways from being done, so it could be worth doing on the current implementation.

**Comment by gperinazzo** [comment]
Unless we use an external data-store to keep track, any solution will not work if the message is redelivered to another consumer (in the case of a shared subscription) or if the consumer is restarted. 

There is an effort to make the broker handle acks for single messages (tracked in [PIP 54](https://github.com/apache/pulsar/wiki/PIP-54:-Acknowledgement-for-local-index-of-batch-message)) that will send a bitfield with the batched message to allow the client to skip messages that are already acked.

So I don't think doing the necessary surgery to track redeliveries is a good idea, since it won't be reliable (guarantee that the message is only delivered once), and will eventually be unnecessary.

I'll try implementing the batched ack in the current ack structure. We can do this by having two extra optional fields in the structure: a batch index, and a batch size. The `AckHandler` can check if it has already seen a message from that batch, and start tracking it.

**Comment by stearnsc** [comment]
Ah right, I wasn't thinking about multiple consumers. Okay, that sounds good to me.
