### ISSUE TITLE
Introduce releases

### ISSUE THREAD

**Issue by KannarFr** [streamnative/pulsar-rs#65]
Hi @stearnsc,

Can you introduce releases for crates.io?

**Comment by KannarFr** [comment]
(https://github.com/timberio/vector/pull/1665 would use it, but needs release).

**Comment by KannarFr** [comment]
@stearnsc maybe @Geal could be introduce as comaintainer to help you? WDYT?

**Comment by stearnsc** [comment]
Yep, sorry. I should be able to get to this tomorrow. 

For some context, I had been stalling trying to finish a major rewrite before releasing the next version (probably as a pre-1.0 push), but work got busy and tanked my time, so I don't think it's worth blocking on that.

I'm not opposed to adding @Geal as a maintainer, but would want to chat about his interest first.

**Comment by Geal** [comment]
@stearnsc hi!
So, for the context, @KannarFr works with me at [Clever Cloud](https://www.clever-cloud.com/), an IT automation platform based in France. We'e been doing a lot of Rust work over the years, on projects like the [sozu HTTP proxy](https://github.com/sozu-proxy/sozu) or the [lapin AMQP client](https://github.com/sozu-proxy/lapin), and we started to rely on Pulsar for parts of our infrastructure.
So we need a production ready Pulsar client in Rust (I think there are at least 3 of our internal projects already using pulsar-rs?) and as you've seen this past year, I can contribute to help it get there.

**Comment by Geal** [comment]
BTW, what do you need to finish the rewrite, can we help? :wink: 
Here are the kind of things I'm planning to work on for now:
- reliability testing: as we deploy it more largely, I'm sure we'll encounter a lot of interesting bugs, as we've seen in lapin
- API usability
- compression and message formats
- performance

**Comment by stearnsc** [comment]
Okay! I've just published 0.3, and I started a tracking issue [here](https://github.com/wyyerd/pulsar-rs/issues/67 for the 1.0 changes I'd like. That list in the issue is probably incomplete, but roughly I'd like some semblance of parity with the java go clients, or at least the bulk of important features.

**Comment by stearnsc** [comment]
I'll try to get my current 1.0 WIP into a good state for contribution - it's currently in the pre-compile phase.
