### ISSUE TITLE
Handle topic partitioning

### ISSUE THREAD

**Issue by stearnsc** [streamnative/pulsar-rs#7]
Related to https://github.com/wyyerd/pulsar-rs/issues/1 both producers and consumers should use service discovery correctly to handle partitioned topics

https://pulsar.apache.org/docs/en/concepts-messaging/#partitioned-topics

**Comment by Geal** [comment]
the #17 PR handles partitioned topic lookup

**Comment by stearnsc** [comment]
resolved by https://github.com/wyyerd/pulsar-rs/pull/17
