### ISSUE TITLE
support hostname as address

### ISSUE THREAD

**Issue by KannarFr** [streamnative/pulsar-rs#70]
Hi,

Currently the client uses only ip address to reach pulsar.

It would be great to support hostname url, dig them and use random ip, if the client stop because this ip becomes unreachable or something try to switch on other and again for resiliency.

**Comment by Geal** [comment]
done in 5210070

**Comment by ckdarby** [comment]
@Geal [Vector](https://github.com/timberio/vector/blob/cfc418e69476e383c8786c3de8191a5a7eaeb732/Cargo.toml#L160) is currently using this and a couple of us would like to have the hostname as address support added there.

I see you're doing a bunch of refactoring. If possible, let me know when you're all done & I'll check there pulling the latest to see if everything continue to function.

**Comment by Geal** [comment]
@ckdarby the current master already has the fix. The last big API change that comes is #82 (btw if you have opinions about that change, I'm interested).
I'd like to add support for other executors and finish the compression implementation, and then it should be ready for testing :smile:

**Comment by ckdarby** [comment]
@Geal Looks like you've got everything merged in :)

I'll try to build on the Pulsar side with the latest pulsar-rs from here and see if everything is still functioning correctly.

**Comment by KannarFr** [comment]
@ckdarby are you working on this? I need vector pulsar sink healthcheck using the fresh `check_connection()` which should be call on `TopicProducer` used as pulsar sink. There is some stuff to get done because of the async/await part.

**Comment by Geal** [comment]
it's been working properly for a while now, closing this
