### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by cameronpickham** [streamnative/pulsar-rs#87]
I need TLS support in order to connect to my deployed Pulsar server. I was able to get it working by modifying the `pulsar-rs` source to use [tokio-native-tls](https://github.com/tokio-rs/tls/tree/master/tokio-native-tls) in `connection.rs` but wanted to defer to the project maintainers as to the best next steps here.

**Comment by Geal** [comment]
could you post the code somewhere so I can take a look?

**Comment by cameronpickham** [comment]
I just modified the body of `Connection::new` to show that it could work- would probably need to alter the signature of the method so that we have access to the hostname and so that the `TlsConnector` is only applied when TLS is needed.

```
        let address = SocketAddr::from_str(&addr)
            .map_err(|e| ConnectionError::SocketAddr(e.to_string()))?;

        let connector = tokio_native_tls::TlsConnector::from(native_tls::TlsConnector::new().map_err(|e| ConnectionError::Disconnected)?);

        let mut stream = TcpStream::connect(&address)
            .await
            .map(|stream| connector.connect(HOSTNAME, stream))?
            .await
            .map(|stream| tokio_util::codec::Framed::new(stream, Codec))
            .map_err(|e| ConnectionError::Disconnected)?;
```

**Comment by cameronpickham** [comment]
[Here](https://github.com/cameronpickham/pulsar-rs/commit/62708a15d8e06529663d7f76d33fdbbcb46bb935) is my fork, with my hostname hardcoded in

**Comment by Geal** [comment]
ok, with #96 it should work now (but only with certificates coming from CAs in public lists)
